version: '3.7'

services:

  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=schelly
      - POSTGRES_PASSWORD=postgres

  schelly:
    image: flaviostutz/schelly
    ports:
      - 8080:8080
    environment:
      - LOG_LEVEL=debug
      - BACKUP_NAME=schelly-pgdump
      - WEBHOOK_URL=http://schelly-postgres-provider:7070/backups
      - BACKUP_CRON_STRING=0 */1 * * * *
      - RETENTION_MINUTELY=5
      - WEBHOOK_GRACE_TIME=200
      - GRACE_TIME_SECONDS=200

  schelly-postgres-provider:
    image: tiagostutz/schelly-postgres
    build: .
    ports:
      - 7070:7070
    environment:
      - LOG_LEVEL=debug
      - BACKUP_FILE_PATH=/var/backups
      - DATABASE_NAME=schelly
      - DATABASE_CONNECTION_HOST=db
      - DATABASE_CONNECTION_PORT=5432
      - DATABASE_AUTH_USERNAME=postgres
      - DATABASE_AUTH_PASSWORD=postgres
      - USE_AZURE_STORAGE=false
      - "AZURE_STORAGE_ACCOUNT_NAME=xxxxxxxxxx"
      - "AZURE_STORAGE_ACCOUNT_KEY=xxxxxxxxxxx"
      - "AZURE_STORAGE_CONTAINER_NAME=xxxxxxxxxxx"

networks:
  default:
    name: schelly-postgres-net